development:
  adapter: postgresql
  encoding: unicode
  database: eventmanagementapp_development
  pool: 5
  username: deploy
  password: <%= ENV['EVENT_APP_USER_POSTGRES_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: eventmanagementapp_test
  pool: 5
  username: jonnylynchy
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: eventmanagementapp_production
  pool: 5
  username: deploy
  password: <%= ENV['EVENT_APP_USER_POSTGRES_PASSWORD'] %>
