development:
  adapter: sqlite3
  database: eventmanagementapp_development
  host: localhost

test:
  adapter: sqlite3
  database: eventmanagementapp_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: eventmanagementapp_production
  pool: 5
  username: deploy
  password: <%= ENV['EVENT_APP_USER_POSTGRES_PASSWORD'] %>
